In [30]:
import numpy as np 
import pandas as pd
import os

In [ ]:
domain_binary = pd.read_csv('/home/anna/Documents/EcoGenoRisk_Paper_Revisions/Metagnome Functional Profiles/Activated_Sludge_Metagenome_functional_profile', delimiter=" ", header=0)
domain_binary

,Name_of_Genome,1.1.1.1,1.1.1.2,1.1.1.3,1.1.1.4,1.1.1.5,1.1.1.6,1.1.1.7,1.1.1.8,1.1.1.9,...,7.6.2.7,7.6.2.8,7.6.2.9,7.6.2.10,7.6.2.11,7.6.2.12,7.6.2.13,7.6.2.14,7.6.2.15,7.6.2.16
0,3300056625_228_matches.tsv,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,3300056625_197_matches.tsv,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,3300055001_136_matches.tsv,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3300055001_94_matches.tsv,1,1,1,0,0,0,0,0,0,...,1,1,0,1,1,0,0,0,0,0
4,3300056626_306_matches.tsv,0,1,1,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369,3300056827_209_matches.tsv,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1370,3300055001_119_matches.tsv,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1371,3300055001_241_matches.tsv,1,0,1,0,0,0,0,0,0,...,1,1,0,1,1,0,1,1,0,1
1372,3300056759_268_matches.tsv,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1373,3300056759_46_matches.tsv,1,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [26]:
meta_EC = domain_binary.columns.tolist()
# del meta_EC[0]
meta_EC

['Name_of_Genome',
 '1.1.1.1',
 '1.1.1.2',
 '1.1.1.3',
 '1.1.1.4',
 '1.1.1.5',
 '1.1.1.6',
 '1.1.1.7',
 '1.1.1.8',
 '1.1.1.9',
 '1.1.1.10',
 '1.1.1.11',
 '1.1.1.12',
 '1.1.1.13',
 '1.1.1.14',
 '1.1.1.15',
 '1.1.1.16',
 '1.1.1.17',
 '1.1.1.18',
 '1.1.1.19',
 '1.1.1.20',
 '1.1.1.21',
 '1.1.1.22',
 '1.1.1.23',
 '1.1.1.24',
 '1.1.1.25',
 '1.1.1.26',
 '1.1.1.27',
 '1.1.1.28',
 '1.1.1.29',
 '1.1.1.30',
 '1.1.1.31',
 '1.1.1.32',
 '1.1.1.33',
 '1.1.1.34',
 '1.1.1.35',
 '1.1.1.36',
 '1.1.1.37',
 '1.1.1.38',
 '1.1.1.39',
 '1.1.1.40',
 '1.1.1.41',
 '1.1.1.42',
 '1.1.1.43',
 '1.1.1.44',
 '1.1.1.45',
 '1.1.1.46',
 '1.1.1.47',
 '1.1.1.48',
 '1.1.1.49',
 '1.1.1.50',
 '1.1.1.51',
 '1.1.1.52',
 '1.1.1.53',
 '1.1.1.54',
 '1.1.1.55',
 '1.1.1.56',
 '1.1.1.57',
 '1.1.1.58',
 '1.1.1.59',
 '1.1.1.60',
 '1.1.1.61',
 '1.1.1.62',
 '1.1.1.63',
 '1.1.1.64',
 '1.1.1.65',
 '1.1.1.66',
 '1.1.1.67',
 '1.1.1.68',
 '1.1.1.69',
 '1.1.1.70',
 '1.1.1.71',
 '1.1.1.72',
 '1.1.1.73',
 '1.1.1.74',
 '1.1.1.75',
 '1.1.1.76',
 '1.1.1.77',
 '1.1.1.78',
 '1.1.1.79',
 '1.1.1.80',
 '1.1.1.81',
 '1.1.1.82',
 '1.1.1.83',
 '1.1.1.84',
 '1.1.1.85',
 '1.1.1.86',
 '1.1.1.87',
 '1.1.1.88',
 '1.1.1.89',
 '1.1.1.90',
 '1.1.1.91',
 '1.1.1.92',
 '1.1.1.93',
 '1.1.1.94',
 '1.1.1.95',
 '1.1.1.96',
 '1.1.1.97',
 '1.1.1.98',
 '1.1.1.99',
 '1.1.1.100',
 '1.1.1.101',
 '1.1.1.102',
 '1.1.1.103',
 '1.1.1.104',
 '1.1.1.105',
 '1.1.1.106',
 '1.1.1.107',
 '1.1.1.108',
 '1.1.1.109',
 '1.1.1.110',
 '1.1.1.111',
 '1.1.1.112',
 '1.1.1.113',
 '1.1.1.114',
 '1.1.1.115',
 '1.1.1.116',
 '1.1.1.117',
 '1.1.1.118',
 '1.1.1.119',
 '1.1.1.120',
 '1.1.1.121',
 '1.1.1.122',
 '1.1.1.123',
 '1.1.1.124',
 '1.1.1.125',
 '1.1.1.126',
 '1.1.1.127',
 '1.1.1.128',
 '1.1.1.129',
 '1.1.1.130',
 '1.1.1.131',
 '1.1.1.132',
 '1.1.1.133',
 '1.1.1.134',
 '1.1.1.135',
 '1.1.1.136',
 '1.1.1.137',
 '1.1.1.138',
 '1.1.1.139',
 '1.1.1.140',
 '1.1.1.141',
 '1.1.1.142',
 '1.1.1.143',
 '1.1.1.144',
 '1.1.1.145',
 '1.1.1.146',
 '1.1.1.147',
 '1.1.1.148',
 '1.1.1.149',
 '1.1.1.150',
 '1.1.1.151',
 '1.1.1.152',
 '1.1.1.153',
 '1.1.1.154',
 '1.1.1.155',
 '1.1.1.156',
 '1.1.1.157',
 '1.1.1.158',
 '1.1.1.159',
 '1.1.1.160',
 '1.1.1.161',
 '1.1.1.162',
 '1.1.1.163',
 '1.1.1.164',
 '1.1.1.165',
 '1.1.1.166',
 '1.1.1.167',
 '1.1.1.168',
 '1.1.1.169',
 '1.1.1.170',
 '1.1.1.171',
 '1.1.1.172',
 '1.1.1.173',
 '1.1.1.174',
 '1.1.1.175',
 '1.1.1.176',
 '1.1.1.177',
 '1.1.1.178',
 '1.1.1.179',
 '1.1.1.180',
 '1.1.1.181',
 '1.1.1.182',
 '1.1.1.183',
 '1.1.1.184',
 '1.1.1.185',
 '1.1.1.186',
 '1.1.1.187',
 '1.1.1.188',
 '1.1.1.189',
 '1.1.1.190',
 '1.1.1.191',
 '1.1.1.192',
 '1.1.1.193',
 '1.1.1.194',
 '1.1.1.195',
 '1.1.1.196',
 '1.1.1.197',
 '1.1.1.198',
 '1.1.1.199',
 '1.1.1.200',
 '1.1.1.201',
 '1.1.1.202',
 '1.1.1.203',
 '1.1.1.204',
 '1.1.1.205',
 '1.1.1.206',
 '1.1.1.207',
 '1.1.1.208',
 '1.1.1.209',
 '1.1.1.210',
 '1.1.1.211',
 '1.1.1.212',
 '1.1.1.213',
 '1.1.1.214',
 '1.1.1.215',
 '1.1.1.216',
 '1.1.1.217',
 '1.1.1.218',
 '1.1.1.219',
 '1.1.1.220',
 '1.1.1.221',
 '1.1.1.222',
 '1.1.1.223',
 '1.1.1.224',
 '1.1.1.225',
 '1.1.1.226',
 '1.1.1.227',
 '1.1.1.228',
 '1.1.1.229',
 '1.1.1.230',
 '1.1.1.231',
 '1.1.1.232',
 '1.1.1.233',
 '1.1.1.234',
 '1.1.1.235',
 '1.1.1.236',
 '1.1.1.237',
 '1.1.1.238',
 '1.1.1.239',
 '1.1.1.240',
 '1.1.1.241',
 '1.1.1.242',
 '1.1.1.243',
 '1.1.1.244',
 '1.1.1.245',
 '1.1.1.246',
 '1.1.1.247',
 '1.1.1.248',
 '1.1.1.249',
 '1.1.1.250',
 '1.1.1.251',
 '1.1.1.252',
 '1.1.1.253',
 '1.1.1.254',
 '1.1.1.255',
 '1.1.1.256',
 '1.1.1.257',
 '1.1.1.258',
 '1.1.1.259',
 '1.1.1.260',
 '1.1.1.261',
 '1.1.1.262',
 '1.1.1.263',
 '1.1.1.264',
 '1.1.1.265',
 '1.1.1.266',
 '1.1.1.267',
 '1.1.1.268',
 '1.1.1.269',
 '1.1.1.270',
 '1.1.1.271',
 '1.1.1.272',
 '1.1.1.273',
 '1.1.1.274',
 '1.1.1.275',
 '1.1.1.276',
 '1.1.1.277',
 '1.1.1.278',
 '1.1.1.279',
 '1.1.1.280',
 '1.1.1.281',
 '1.1.1.282',
 '1.1.1.283',
 '1.1.1.284',
 '1.1.1.285',
 '1.1.1.286',
 '1.1.1.287',
 '1.1.1.288',
 '1.1.1.289',
 '1.1.1.290',
 '1.1.1.291',
 '1.1.1.292',
 '1.1.1.293',
 '1.1.1.294',
 '1.1.1.295',
 '1.1.1.296',
 '1.1.1.297',
 '1.1.1.298',
 '1.1.1.299',
 '1.1.1.300',
 '1.1.1.301',
 '1.1.1.302',
 '1.1.1.303',
 '1.1.1.304',
 '1.1.1.305',
 '1.1.1.306',
 '1.1.1.307',
 '1.1.1.308',
 '1.1.1.309',
 '1.1.1.310',
 '1.1.1.311',
 '1.1.1.312',
 '1.1.1.313',
 '1.1.1.314',
 '1.1.1.315',
 '1.1.1.316',
 '1.1.1.317',
 '1.1.1.318',
 '1.1.1.319',
 '1.1.1.320',
 '1.1.1.321',
 '1.1.1.322',
 '1.1.1.323',
 '1.1.1.324',
 '1.1.1.325',
 '1.1.1.326',
 '1.1.1.327',
 '1.1.1.328',
 '1.1.1.329',
 '1.1.1.330',
 '1.1.1.331',
 '1.1.1.332',
 '1.1.1.333',
 '1.1.1.334',
 '1.1.1.335',
 '1.1.1.336',
 '1.1.1.337',
 '1.1.1.338',
 '1.1.1.339',
 '1.1.1.340',
 '1.1.1.341',
 '1.1.1.342',
 '1.1.1.343',
 '1.1.1.344',
 '1.1.1.345',
 '1.1.1.346',
 '1.1.1.347',
 '1.1.1.348',
 '1.1.1.349',
 '1.1.1.350',
 '1.1.1.351',
 '1.1.1.352',
 '1.1.1.353',
 '1.1.1.354',
 '1.1.1.355',
 '1.1.1.356',
 '1.1.1.357',
 '1.1.1.358',
 '1.1.1.359',
 '1.1.1.360',
 '1.1.1.361',
 '1.1.1.362',
 '1.1.1.363',
 '1.1.1.364',
 '1.1.1.365',
 '1.1.1.366',
 '1.1.1.367',
 '1.1.1.368',
 '1.1.1.369',
 '1.1.1.370',
 '1.1.1.371',
 '1.1.1.372',
 '1.1.1.373',
 '1.1.1.374',
 '1.1.1.375',
 '1.1.1.376',
 '1.1.1.377',
 '1.1.1.378',
 '1.1.1.379',
 '1.1.1.380',
 '1.1.1.381',
 '1.1.1.382',
 '1.1.1.383',
 '1.1.1.384',
 '1.1.1.385',
 '1.1.1.386',
 '1.1.1.387',
 '1.1.1.388',
 '1.1.1.389',
 '1.1.1.390',
 '1.1.1.391',
 '1.1.1.392',
 '1.1.1.393',
 '1.1.1.394',
 '1.1.1.395',
 '1.1.1.396',
 '1.1.1.397',
 '1.1.1.398',
 '1.1.1.399',
 '1.1.1.400',
 '1.1.1.401',
 '1.1.1.402',
 '1.1.1.403',
 '1.1.1.404',
 '1.1.1.405',
 '1.1.1.406',
 '1.1.1.407',
 '1.1.1.408',
 '1.1.1.409',
 '1.1.1.410',
 '1.1.1.411',
 '1.1.1.412',
 '1.1.1.413',
 '1.1.1.414',
 '1.1.1.415',
 '1.1.1.416',
 '1.1.1.417',
 '1.1.1.418',
 '1.1.1.419',
 '1.1.1.420',
 '1.1.1.421',
 '1.1.1.422',
 '1.1.1.423',
 '1.1.1.424',
 '1.1.1.425',
 '1.1.1.426',
 '1.1.1.427',
 '1.1.1.428',
 '1.1.1.429',
 '1.1.1.430',
 '1.1.1.431',
 '1.1.1.432',
 '1.1.1.433',
 '1.1.1.434',
 '1.1.1.435',
 '1.1.1.436',
 '1.1.1.437',
 '1.1.1.n1',
 '1.1.1.n2',
 '1.1.1.n3',
 '1.1.1.n4',
 '1.1.1.n5',
 '1.1.1.n6',
 '1.1.1.n7',
 '1.1.1.n8',
 '1.1.1.n9',
 '1.1.1.n10',
 '1.1.1.n11',
 '1.1.1.n12',
 '1.1.1.n13',
 '1.1.1.n14',
 '1.1.2.1',
 '1.1.2.2',
 '1.1.2.3',
 '1.1.2.4',
 '1.1.2.5',
 '1.1.2.6',
 '1.1.2.7',
 '1.1.2.8',
 '1.1.2.9',
 '1.1.2.10',
 '1.1.2.11',
 '1.1.3.1',
 '1.1.3.2',
 '1.1.3.3',
 '1.1.3.4',
 '1.1.3.5',
 '1.1.3.6',
 '1.1.3.7',
 '1.1.3.8',
 '1.1.3.9',
 '1.1.3.10',
 '1.1.3.11',
 '1.1.3.12',
 '1.1.3.13',
 '1.1.3.14',
 '1.1.3.15',
 '1.1.3.16',
 '1.1.3.17',
 '1.1.3.18',
 '1.1.3.19',
 '1.1.3.20',
 '1.1.3.21',
 '1.1.3.22',
 '1.1.3.23',
 '1.1.3.24',
 '1.1.3.25',
 '1.1.3.26',
 '1.1.3.27',
 '1.1.3.28',
 '1.1.3.29',
 '1.1.3.30',
 '1.1.3.31',
 '1.1.3.32',
 '1.1.3.33',
 '1.1.3.34',
 '1.1.3.35',
 '1.1.3.36',
 '1.1.3.37',
 '1.1.3.38',
 '1.1.3.39',
 '1.1.3.40',
 '1.1.3.41',
 '1.1.3.42',
 '1.1.3.43',
 '1.1.3.44',
 '1.1.3.45',
 '1.1.3.46',
 '1.1.3.47',
 '1.1.3.48',
 '1.1.3.49',
 '1.1.3.50',
 '1.1.4.1',
 '1.1.4.2',
 '1.1.5.1',
 '1.1.5.2',
 '1.1.5.3',
 '1.1.5.4',
 '1.1.5.5',
 '1.1.5.6',
 '1.1.5.7',
 '1.1.5.8',
 '1.1.5.9',
 '1.1.5.10',
 '1.1.5.11',
 '1.1.5.12',
 '1.1.5.13',
 '1.1.5.14',
 '1.1.5.n1',
 '1.1.7.1',
 '1.1.9.1',
 '1.1.98.1',
 '1.1.98.2',
 '1.1.98.3',
 '1.1.98.4',
 '1.1.98.5',
 '1.1.98.6',
 '1.1.98.7',
 '1.1.99.1',
 '1.1.99.2',
 '1.1.99.3',
 '1.1.99.4',
 '1.1.99.5',
 '1.1.99.6',
 '1.1.99.7',
 '1.1.99.8',
 '1.1.99.9',
 '1.1.99.10',
 '1.1.99.11',
 '1.1.99.12',
 '1.1.99.13',
 '1.1.99.14',
 '1.1.99.15',
 '1.1.99.16',
 '1.1.99.17',
 '1.1.99.18',
 '1.1.99.19',
 '1.1.99.20',
 '1.1.99.21',
 '1.1.99.22',
 '1.1.99.23',
 '1.1.99.24',
 '1.1.99.25',
 '1.1.99.26',
 '1.1.99.27',
 '1.1.99.28',
 '1.1.99.29',
 '1.1.99.30',
 '1.1.99.31',
 '1.1.99.32',
 '1.1.99.33',
 '1.1.99.34',
 '1.1.99.35',
 '1.1.99.36',
 '1.1.99.37',
 '1.1.99.38',
 '1.1.99.39',
 '1.1.99.40',
 '1.1.99.41',
 '1.1.99.42',
 '1.2.1.1',
 '1.2.1.2',
 '1.2.1.3',
 '1.2.1.4',
 '1.2.1.5',
 '1.2.1.6',
 '1.2.1.7',
 '1.2.1.8',
 '1.2.1.9',
 '1.2.1.10',
 '1.2.1.11',
 '1.2.1.12',
 '1.2.1.13',
 '1.2.1.14',
 '1.2.1.15',
 '1.2.1.16',
 '1.2.1.17',
 '1.2.1.18',
 '1.2.1.19',
 '1.2.1.20',
 '1.2.1.21',
 '1.2.1.22',
 '1.2.1.23',
 '1.2.1.24',
 '1.2.1.25',
 '1.2.1.26',
 '1.2.1.27',
 '1.2.1.28',
 '1.2.1.29',
 '1.2.1.30',
 '1.2.1.31',
 '1.2.1.32',
 '1.2.1.33',
 '1.2.1.34',
 '1.2.1.35',
 '1.2.1.36',
 '1.2.1.37',
 '1.2.1.38',
 '1.2.1.39',
 '1.2.1.40',
 '1.2.1.41',
 '1.2.1.42',
 '1.2.1.43',
 '1.2.1.44',
 '1.2.1.45',
 '1.2.1.46',
 '1.2.1.47',
 '1.2.1.48',
 '1.2.1.49',
 '1.2.1.50',
 '1.2.1.51',
 '1.2.1.52',
 '1.2.1.53',
 '1.2.1.54',
 '1.2.1.55',
 '1.2.1.56',
 '1.2.1.57',
 '1.2.1.58',
 '1.2.1.59',
 '1.2.1.60',
 '1.2.1.61',
 '1.2.1.62',
 '1.2.1.63',
 '1.2.1.64',
 '1.2.1.65',
 '1.2.1.66',
 '1.2.1.67',
 '1.2.1.68',
 '1.2.1.69',
 '1.2.1.70',
 '1.2.1.71',
 '1.2.1.72',
 '1.2.1.73',
 '1.2.1.74',
 '1.2.1.75',
 '1.2.1.76',
 '1.2.1.77',
 '1.2.1.78',
 '1.2.1.79',
 '1.2.1.80',
 '1.2.1.81',
 '1.2.1.82',
 '1.2.1.83',
 '1.2.1.84',
 '1.2.1.85',
 '1.2.1.86',
 '1.2.1.87',
 '1.2.1.88',
 '1.2.1.89',
 '1.2.1.90',
 '1.2.1.91',
 '1.2.1.92',
 '1.2.1.93',
 '1.2.1.94',
 '1.2.1.95',
 '1.2.1.96',
 '1.2.1.97',
 '1.2.1.98',
 '1.2.1.99',
 '1.2.1.100',
 '1.2.1.101',
 '1.2.1.102',
 '1.2.1.103',
 '1.2.1.104',
 '1.2.1.105',
 '1.2.1.106',
 '1.2.1.107',
 '1.2.1.n1',
 '1.2.1.n2',
 '1.2.1.n3',
 '1.2.2.1',
 '1.2.2.2',
 '1.2.2.3',
 '1.2.2.4',
 '1.2.3.1',
 '1.2.3.2',
 '1.2.3.3',
 '1.2.3.4',
 '1.2.3.5',
 '1.2.3.6',
 '1.2.3.7',
 '1.2.3.8',
 '1.2.3.9',
 '1.2.3.10',
 '1.2.3.11',
 '1.2.3.12',
 '1.2.3.13',
 '1.2.3.14',
 '1.2.3.15',
 '1.2.4.1',
 '1.2.4.2',
 '1.2.4.3',
 '1.2.4.4',
 '1.2.5.1',
 '1.2.5.2',
 '1.2.5.3',
 '1.2.7.1',
 '1.2.7.2',
 '1.2.7.3',
 '1.2.7.4',
 '1.2.7.5',
 '1.2.7.6',
 '1.2.7.7',
 '1.2.7.8',
 '1.2.7.9',
 '1.2.7.10',
 '1.2.7.11',
 '1.2.7.12',
 '1.2.98.1',
 '1.2.99.1',
 '1.2.99.2',
 '1.2.99.3',
 '1.2.99.4',
 '1.2.99.5',
 '1.2.99.6',
 '1.2.99.7',
 '1.2.99.8',
 '1.2.99.9',
 '1.2.99.10',
 '1.3.1.1',
 '1.3.1.2',
 '1.3.1.3',
 '1.3.1.4',
 '1.3.1.5',
 '1.3.1.6',
 '1.3.1.7',
 '1.3.1.8',
 '1.3.1.9',
 '1.3.1.10',
 '1.3.1.11',
 '1.3.1.12',
 '1.3.1.13',
 '1.3.1.14',
 '1.3.1.15',
 '1.3.1.16',
 '1.3.1.17',
 '1.3.1.18',
 '1.3.1.19',
 '1.3.1.20',
 '1.3.1.21',
 '1.3.1.22',
 '1.3.1.23',
 '1.3.1.24',
 '1.3.1.25',
 '1.3.1.26',
 '1.3.1.27',
 '1.3.1.28',
 '1.3.1.29',
 '1.3.1.30',
 '1.3.1.31',
 '1.3.1.32',
 '1.3.1.33',
 '1.3.1.34',
 '1.3.1.35',
 '1.3.1.36',
 '1.3.1.37',
 '1.3.1.38',
 '1.3.1.39',
 '1.3.1.40',
 '1.3.1.41',
 '1.3.1.42',
 '1.3.1.43',
 '1.3.1.44',
 '1.3.1.45',
 '1.3.1.46',
 '1.3.1.47',
 '1.3.1.48',
 '1.3.1.49',
 '1.3.1.50',
 '1.3.1.51',
 '1.3.1.52',
 '1.3.1.53',
 '1.3.1.54',
 '1.3.1.55',
 '1.3.1.56',
 '1.3.1.57',
 '1.3.1.58',
 '1.3.1.59',
 '1.3.1.60',
 '1.3.1.61',
 '1.3.1.62',
 '1.3.1.63',
 '1.3.1.64',
 '1.3.1.65',
 '1.3.1.66',
 '1.3.1.67',
 '1.3.1.68',
 '1.3.1.69',
 '1.3.1.70',
 '1.3.1.71',
 '1.3.1.72',
 '1.3.1.73',
 '1.3.1.74',
 '1.3.1.75',
 '1.3.1.76',
 '1.3.1.77',
 '1.3.1.78',
 '1.3.1.79',
 '1.3.1.80',
 '1.3.1.81',
 '1.3.1.82',
 '1.3.1.83',
 '1.3.1.84',
 '1.3.1.85',
 '1.3.1.86',
 '1.3.1.87',
 '1.3.1.88',
 '1.3.1.89',
 '1.3.1.90',
 '1.3.1.91',
 '1.3.1.92',
 '1.3.1.93',
 '1.3.1.94',
 '1.3.1.95',
 '1.3.1.96',
 '1.3.1.97',
 '1.3.1.98',
 '1.3.1.99',
 '1.3.1.100',
 '1.3.1.101',
 '1.3.1.102',
 '1.3.1.103',
 '1.3.1.104',
 '1.3.1.105',
 '1.3.1.106',
 '1.3.1.107',
 '1.3.1.108',
 '1.3.1.109',
 '1.3.1.110',
 '1.3.1.111',
 '1.3.1.112',
 '1.3.1.113',
 '1.3.1.114',
 '1.3.1.115',
 '1.3.1.116',
 '1.3.1.117',
 '1.3.1.118',
 '1.3.1.119',
 '1.3.1.120',
 '1.3.1.121',
 '1.3.1.122',
 '1.3.1.123',
 '1.3.1.124',
 '1.3.1.125',
 '1.3.1.126',
 '1.3.1.n1',
 '1.3.1.n2',
 '1.3.1.n3',
 '1.3.2.1',
 '1.3.2.2',
 '1.3.2.3',
 '1.3.2.4',
 '1.3.3.1',
 '1.3.3.2',
 '1.3.3.3',
 '1.3.3.4',
 '1.3.3.5',
 '1.3.3.6',
 '1.3.3.7',
 '1.3.3.8',
 '1.3.3.9',
 '1.3.3.10',
 '1.3.3.11',
 '1.3.3.12',
 '1.3.3.13',
 '1.3.3.14',
 '1.3.3.15',
 '1.3.3.16',
 '1.3.3.17',
 '1.3.4.1',
 '1.3.5.1',
 '1.3.5.2',
 '1.3.5.3',
 '1.3.5.4',
 '1.3.5.5',
 '1.3.5.6',
 '1.3.7.1',
 '1.3.7.2',
 '1.3.7.3',
 '1.3.7.4',
 '1.3.7.5',
 '1.3.7.6',
 '1.3.7.7',
 '1.3.7.8',
 '1.3.7.9',
 '1.3.7.10',
 '1.3.7.11',
 '1.3.7.12',
 '1.3.7.13',
 '1.3.7.14',
 '1.3.7.15',
 '1.3.8.1',
 '1.3.8.2',
 '1.3.8.3',
 '1.3.8.4',
 '1.3.8.5',
 '1.3.8.6',
 '1.3.8.7',
 '1.3.8.8',
 '1.3.8.9',
 '1.3.8.10',
 '1.3.8.11',
 '1.3.8.12',
 '1.3.8.13',
 '1.3.8.14',
 '1.3.8.15',
 '1.3.8.16',
 '1.3.8.17',
 '1.3.98.1',
 '1.3.98.2',
 '1.3.98.3',
 '1.3.98.4',
 '1.3.98.5',
 '1.3.98.6',
 '1.3.98.7',
 '1.3.99.1',
 '1.3.99.2',
 '1.3.99.3',
 '1.3.99.4',
 '1.3.99.5',
 '1.3.99.6',
 '1.3.99.7',
 '1.3.99.8',
 '1.3.99.9',
 '1.3.99.10',
 '1.3.99.11',
 '1.3.99.12',
 '1.3.99.13',
 '1.3.99.14',
 '1.3.99.15',
 '1.3.99.16',
 '1.3.99.17',
 '1.3.99.18',
 '1.3.99.19',
 '1.3.99.20',
 '1.3.99.21',
 '1.3.99.22',
 '1.3.99.23',
 '1.3.99.24',
 '1.3.99.25',
 '1.3.99.26',
 '1.3.99.27',
 '1.3.99.28',
 '1.3.99.29',
 '1.3.99.30',
 '1.3.99.31',
 '1.3.99.32',
 '1.3.99.33',
 '1.3.99.34',
 '1.3.99.35',
 '1.3.99.36',
 '1.3.99.37',
 '1.3.99.38',
 '1.3.99.39',
 '1.3.99.40',
 '1.3.99.41',
 '1.3.99.n1',
 '1.3.99.n2',
 '1.3.99.n3',
 '1.4.1.1',
 '1.4.1.2',
 '1.4.1.3',
 '1.4.1.4',
 '1.4.1.5',
 '1.4.1.6',
 '1.4.1.7',
 '1.4.1.8',
 '1.4.1.9',
 '1.4.1.10',
 '1.4.1.11',
 '1.4.1.12',
 '1.4.1.13',
 '1.4.1.14',
 '1.4.1.15',
 '1.4.1.16',
 '1.4.1.17',
 '1.4.1.18',
 '1.4.1.19',
 '1.4.1.20',
 ...]

In [27]:
synbio_df = pd.read_csv('/home/anna/Documents/EcoGenoRisk_Paper_Revisions/Biopesticide Function Profiles/Baccilus_Licheniformis.faa_functional_profile', delimiter=" ", header = 0)
synbio_df

,Name_of_Genome,1.1.1.1,1.1.1.2,1.1.1.3,1.1.1.4,1.1.1.5,1.1.1.6,1.1.1.7,1.1.1.8,1.1.1.9,...,7.6.2.7,7.6.2.8,7.6.2.9,7.6.2.10,7.6.2.11,7.6.2.12,7.6.2.13,7.6.2.14,7.6.2.15,7.6.2.16
0,Baccilus_Licheniformis.faa_matches.tsv,0,0,1,0,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0

In [28]:
filtered_df = synbio_df.filter(items = meta_EC, axis = 1)
filtered_df

,Name_of_Genome,1.1.1.1,1.1.1.2,1.1.1.3,1.1.1.4,1.1.1.5,1.1.1.6,1.1.1.7,1.1.1.8,1.1.1.9,...,7.6.2.7,7.6.2.8,7.6.2.9,7.6.2.10,7.6.2.11,7.6.2.12,7.6.2.13,7.6.2.14,7.6.2.15,7.6.2.16
0,Baccilus_Licheniformis.faa_matches.tsv,0,0,1,0,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0

In [29]:
# final = pd.concat([name, metagenome_filtered], axis = 1)
# final

In [37]:
directory = '/home/anna/Documents/EcoGenoRisk_Paper_Revisions/Biopesticide Function Profiles'
for file in os.listdir(directory): 
    path = os.path.join(directory, file)
    synbio_df = pd.read_csv(path, delimiter=" ", header = 0)
    filtered_df = synbio_df.filter(items = meta_EC, axis = 1)
    new_dir = '/home/anna/Documents/EcoGenoRisk_Paper_Revisions/Biopesticide_parsed/' + file
    filtered_df.to_csv(new_dir, sep = ' ', index = False, header=True)

In [35]:
check = pd.read_csv('/home/anna/Documents/EcoGenoRisk_Paper_Revisions/Biopesticide_parsed/Baccilus_Licheniformis.faa_functional_profile', delimiter=" ", header = 0)
len(check.columns)

8270

In [38]:
directory2 = '/home/anna/Documents/EcoGenoRisk_Paper_Revisions/Biopesticide_parsed'
for file in os.listdir(directory2):
    path = os.path.join(directory2, file)
    df = pd.read_csv(path, delimiter=" ", header = 0)
    print(len(df.columns))

8270
8270
8270
8270
8270
8270
8270
8270
8270
8270